# Generated by Django 5.0 on 2026-02-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='initial_balance',
        ),
    ]
